### ISSUE TITLE
How to write to a file?

### ISSUE THREAD

**Issue by serv** [pinojs/express-pino-logger#28]
Reading https://getpino.io/#/docs/api?id=destination-sonicboom-writablestream-string, I am trying to write the log to a file.

When I write 
`const pino = require('express-pino-logger')('./logs');` 

I get error

```
/home/jason/projects/node/h1bhub-app/node_modules/pino-http/logger.js:15
  opts.serializers = opts.serializers || {}
                   ^

TypeError: Cannot create property 'serializers' on string './logs'
    at pinoLogger (/home/jason/projects/node/h1bhub-app/node_modules/pino-http/logger.js:15:20)
    at Object.<anonymous> (/home/jason/projects/node/h1bhub-app/index.js:3:44)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! h1bhub-app@0.0.1 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the h1bhub-app@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jason/.npm/_logs/2019-03-10T20_57_50_633Z-debug.log

```

Any idea why?

**Comment by mcollina** [comment]
The full API is defined in https://github.com/pinojs/pino-http#pinohttpopts-stream.

**Comment by serv** [comment]
```
const pino = require("pino")("./logs/info.log");
const expressPino = require("express-pino-logger")({
  logger: pino
});
app.use(expressPino);
```

This setup will write to ./logs/info.log

**Comment by kelly-tock** [comment]
maybe pino.destination doesn't satisfy this check?

```
if (opts && opts._writableState) {
    stream = opts
    opts = null
  }
```

that is in pino-http?
