### ISSUE TITLE
prevLogger.child is not a function

### ISSUE THREAD

**Issue by MarkusAnthony** [pinojs/express-pino-logger#31]
I am getting the following error:

C:\backend\node_modules\pino-http\logger.js:83
    logger = prevLogger.child(opts)
                        ^
TypeError: prevLogger.child is not a function
    at wrapChild (C:\backend\node_modules\pino-http\logger.js:83:25)
    at pinoLogger (C:\backend\node_modules\pino-http\logger.js:32:16)
    at Object.<anonymous> (C:\backend\src\routes\auth.js:15:51)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```
routes/signin.js:

const router = express.Router();
const pino = require('pino');
const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const expressPino = require('express-pino-logger')({
  logger: pino
})

router.use(expressPino);

```

-Markus

**Comment by MarkusAnthony** [comment]
I was using it wrong:

```
const router = express.Router();
const pino = require('pino');
const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const expressPino = require('express-pino-logger');  //modified
const expressLogger = expressPino({ logger:log });  //added
router.use(expressLogger) //modified
```

-Markus

**Comment by MarkusAnthony** [comment]
I was using it wrong:

```
const router = express.Router();
const pino = require('pino');
const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const expressPino = require('express-pino-logger');  //modified
const expressLogger = expressPino({ logger:log });  //added
router.use(expressLogger) //modified
```

-Markus
