### ISSUE TITLE
Doesn't print stack trace

### ISSUE THREAD

**Issue by ronag** [pinojs/express-pino-logger#7]
Using the following error handler together with `express-pino-logger`:

```javascript
  app.use((err, req, res, next) => {
    const httpError = createHTTPError(err)

    if (httpError.status === 500) {
      req.log.error(err)
    }

    if (res.headersSent) {
      return req.socket.destroy()
    }

    res.status(httpError.status)

    res.send(
      httpError.expose || !config.isProduction
        ? httpError.message
        : '500 Internal Server Error'
      )
  })
```

I would expect that  `req.log.error(err)` would at least print the stack trace in development mode. However, it just prints the `req` and `res` objects.

```
 res: {
      "statusCode": 500
 }
 req: {
     ...
 }
```

**Comment by mcollina** [comment]
Weird, it should be handled in https://github.com/pinojs/pino/blob/master/pino.js#L243.
We'll investigate.

**Comment by mcollina** [comment]
@ronag I cannot reproduce, can you please upload a full example?

https://github.com/pinojs/express-pino-logger/blob/master/example.js#L13-L21 correctly prints:
```
$ node example.js | pino
[2016-11-27T14:26:52.803Z] ERROR (5491 on MacBook-Pro-di-Matteo.local): kaboom
    Error: kaboom
        at /Users/matteo/Repositories/express-pino-logger/example.js:14:8
        at Layer.handle [as handle_request] (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/layer.js:95:5)
        at next (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/layer.js:95:5)
        at /Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/index.js:277:22
        at Function.process_params (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/index.js:330:12)
        at next (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/index.js:271:10)
        at loggingMiddleware (/Users/matteo/Repositories/express-pino-logger/node_modules/pino-http/logger.js:52:7)
        at Layer.handle [as handle_request] (/Users/matteo/Repositories/express-pino-logger/node_modules/express/lib/router/layer.js:95:5)
[2016-11-27T14:26:52.810Z] INFO (5491 on MacBook-Pro-di-Matteo.local): request completed
    res: {
      "statusCode": 500,
      "header": "HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nDate: Sun, 27 Nov 2016 14:26:52 GMT\r\nConnection: keep-alive\r\nContent-Length: 5\r\n\r\n"
    }
    responseTime: 7
    req: {
      "id": 1,
      "method": "GET",
      "url": "/error",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.49.1",
        "accept": "*/*"
      },
      "remoteAddress": "::1",
      "remotePort": 59328
    }
```

**Comment by mcollina** [comment]
Closing for inactivity, feel free to reopen if I'm mistaken!
